# NUMPY KUTUPHANESI

In [1]:
import numpy as np


In [13]:
list1=np.array([2,6,500,0])
list2=np.array([9,5,6,555])

In [7]:
list1*list2

array([  18,   30, 3000,    0])

In [8]:
new_array=np.array([2,3.5,6])
print(new_array)
#hepsini float veri tipine dönüştürdü


[2.  3.5 6. ]


In [11]:
new_array1=np.array([2,3.5,6],dtype="int")
print(new_array1)
#hepsini int değere  dönüştürdü

[2 3 6]


In [8]:
matrix=np.random.randint(0,10,(5,5))
matrix

array([[8, 9, 9, 1, 5],
       [0, 3, 1, 0, 3],
       [6, 5, 9, 5, 0],
       [7, 2, 4, 9, 5],
       [5, 3, 0, 5, 3]])

In [9]:
# sum
np.sum(matrix)

107

In [14]:
matrix.dtype

dtype('int32')

In [16]:
np.ones((1,4))

array([[1., 1., 1., 1.]])

In [21]:
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [26]:
np.arange(4,9)

array([4, 5, 6, 7, 8])

In [27]:
np.random.rand(3,4)

array([[0.41002406, 0.4107356 , 0.18420452, 0.7278857 ],
       [0.26415187, 0.68431055, 0.46567476, 0.01118659],
       [0.05480105, 0.66548482, 0.22645939, 0.23153399]])

In [29]:
np.random.randn(3,3)

array([[ 1.52129783, -0.77446541,  1.58610493],
       [-0.63590709,  0.47740095, -0.43752353],
       [-0.59418819,  1.04682876,  2.3902323 ]])

In [7]:
difference=np.arange(1,21)
difference

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
#reshape komutu
difference.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
# max() ve argmax()
#max değerin indexini verir
difference.argmax()

19

In [11]:
#maximum değereri verir
difference.max()

20

In [14]:
#concatenate
np.concatenate([list1,list2])

array([  2,   6, 500,   0,   9,   5,   6, 555])

In [28]:
array=np.arange(1,7).reshape(3,2)
array2=np.array([[3,2],
                [4,6],
                [8,9]])
array3=np.concatenate([array,array2],axis=1)
#axis 0 satır bazlı axis 1 sütun bazlı birleştirme yapar
array3

array([[1, 2, 3, 2],
       [3, 4, 4, 6],
       [5, 6, 8, 9]])

In [29]:
array4=np.concatenate([array,array2],axis=0)
array4

array([[1, 2],
       [3, 4],
       [5, 6],
       [3, 2],
       [4, 6],
       [8, 9]])

In [39]:
array5=np.arange(1,500)
x,y,z,t=np.split(array5,[100,150,300])

print(f"x degeri:{x}\ny_degeri:{y}")

x degeri:[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
y_degeri:[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
 137 138 139 140 141 142 143 144 145 146 147 148 149 150]


In [43]:
array6=np.arange(0,20).reshape(5,4)
array6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
np.split(array6,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [48]:
#indexleme
array8=np.random.randint(0,10,(5,9))

In [49]:
array8

array([[1, 9, 5, 5, 4, 4, 6, 3, 2],
       [8, 5, 1, 7, 1, 1, 4, 2, 3],
       [6, 3, 3, 6, 1, 8, 5, 8, 2],
       [1, 0, 6, 8, 2, 9, 4, 9, 3],
       [1, 7, 4, 7, 8, 9, 4, 8, 7]])

In [59]:
array8[2,2]

3

In [83]:
#sutun indexe erişmew
array8[1:4,0:5]

array([[8, 5, 1, 7, 1],
       [6, 3, 3, 6, 1],
       [1, 0, 6, 8, 2]])

In [ ]:
array8[1:4,0:5]

In [79]:
array9=np.array([2,3,3,36,645,66,66,85])
array9[2:-3]

array([  3,  36, 645])

In [84]:
#index değerini değiştirme
array9[-1]=20

In [85]:
array9

array([  2,   3,   3,  36, 645,  66,  66,  20])

In [88]:
array8[:,0] =[5,5,5,5,5]
array8

array([[5, 9, 5, 5, 4, 4, 6, 3, 2],
       [5, 5, 1, 7, 1, 1, 4, 2, 3],
       [5, 3, 3, 6, 1, 8, 5, 8, 2],
       [5, 0, 6, 8, 2, 9, 4, 9, 3],
       [5, 7, 4, 7, 8, 9, 4, 8, 7]])

## Fancy index 

In [95]:
list1=np.arange(0,100,2)
fancy_index=np.arange(20,40)
list1[fancy_index]

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72,
       74, 76, 78])

In [1]:
import numpy as np

In [2]:
# İstatistiksel fonksiyonlar

In [19]:
array20=np.random.randint(1,10,(5,5))


In [20]:
array20


array([[6, 8, 4, 8, 4],
       [5, 8, 6, 2, 3],
       [2, 7, 8, 3, 1],
       [3, 1, 1, 3, 7],
       [6, 6, 4, 1, 8]])

In [21]:
array20.mean()

4.6

In [22]:
array20[:,2].mean()

4.6

In [27]:
np.median(array20[:,2])


4.0

In [28]:
np.mean(array20[:,2])

4.6

In [29]:
np.amax(array20[:,2])

8

In [30]:
np.std(array20[:,2])

2.33238075793812

In [31]:
np.var(array20[:,2])

5.4399999999999995

In [32]:
np.sort(array20[:,2])

array([1, 4, 4, 6, 8])

In [33]:
array20

array([[6, 8, 4, 8, 4],
       [5, 8, 6, 2, 3],
       [2, 7, 8, 3, 1],
       [3, 1, 1, 3, 7],
       [6, 6, 4, 1, 8]])

In [34]:
np.where(array20[:,2]>5)

(array([1, 2], dtype=int64),)

## PANDAS KÜTÜPHANESİ


In [138]:
import pandas as pd
import numpy as np

#### Pandas serileri index numaraları ile beraber tutulur. Özellikle Pandas kütüphaneleri kullanım noktasında çok büyük avantajlar sağlamakatadır özellikle veri analizi ve veri biliminin olmassa olmazıdır diyebiliriz. 

In [92]:
series1=pd.Series([10,20,30,40],dtype=float)
series1

0    10.0
1    20.0
2    30.0
3    40.0
dtype: float64

In [93]:
# index degerlerini istedigimiz sekilde kendimiz isimlendirebilmekteyiz

In [94]:
#Deger sayıları esit olmalıdır.
Notes=[65,23,85,52,66,88]
Students=["Ahmet","Mehmet","Sahibe","Saniye","Sukru","Halit"]

In [95]:
list_notes=pd.Series(data=Notes,index=Students,dtype=float)

In [96]:
list_notes

Ahmet     65.0
Mehmet    23.0
Sahibe    85.0
Saniye    52.0
Sukru     66.0
Halit     88.0
dtype: float64

In [97]:
type(list_notes)

pandas.core.series.Series

### Pd series with Dictionary (Sözlük) ;

In [98]:
football_scores_seasontime_gs={"icardi":852,"Muslera":1265,"Sasha_Boey":652}

In [99]:
season=pd.Series(data=football_scores_seasontime_gs)
season

icardi         852
Muslera       1265
Sasha_Boey     652
dtype: int64

In [100]:
season["icardi"]

852

In [64]:
# Numpy array ile pandas serileri oluşturma 

In [65]:
Customers=np.array(["Mustafa","Clark","Joseph"])
Orders_price=np.array([1200,522,633])

In [69]:
Customers_series=pd.Series(data=Orders_price,index=Customers,dtype=float,copy=True)
Customers_series

Mustafa    1200.0
Clark       522.0
Joseph      633.0
dtype: float64

In [70]:
Customers_series.dtype


dtype('float64')

In [71]:
Customers.ndim

1

In [73]:
# .head()----> dizinin ilk 5 elemanını
#.tail()----> dizinin son 5 elemanını getirir. Parantez içerisine eğer sayı  yazılırsa o kadar değer karşımıza çıkar.

Customers_series.head(2)

Mustafa    1200.0
Clark       522.0
dtype: float64

In [74]:
Customers_series.tail(1)

Joseph    633.0
dtype: float64

In [76]:
Customers_series.sort_index()

Clark       522.0
Joseph      633.0
Mustafa    1200.0
dtype: float64

In [77]:
Customers_series.sort_values()

Clark       522.0
Joseph      633.0
Mustafa    1200.0
dtype: float64

In [82]:
# liste içerisine aldık
values= [i for i in Customers_series.values]
values


[1200.0, 522.0, 633.0]

In [84]:
for index,value in Customers_series.items():
    print(f"{index}-{value}.tl alısveris yapmistir.",end="\n")

Mustafa-1200.0.tl alısveris yapmistir.
Clark-522.0.tl alısveris yapmistir.
Joseph-633.0.tl alısveris yapmistir.


## DataFrame

In [101]:
books=np.array(["iktidar","Bitcoin","Million_dolars_habits","Hobbit"])
author=np.array(["Robert_Grenee","Murat_Aksoy","Brian_Tracy","Tolkien"])

In [116]:
pd.DataFrame(books,columns=["Books"],index=author)

Books
Robert_Grenee                iktidar
Murat_Aksoy                  Bitcoin
Brian_Tracy    Million_dolars_habits
Tolkien                       Hobbit

In [120]:
random_array=np.random.randint(0,20,(3,3))
df1=pd.DataFrame(random_array,columns=["val1","val2","val3"],index=[i for i in range(1,4)])

In [121]:
df1.columns=["values1","values2","values3"]

In [122]:
df1

values1  values2  values3
1       16        3        6
2       15       12       15
3       18       15       14

In [127]:
dic1={"x":[10,20,30],
      "y":[30,40,50],
      "z":[50,60,70]}
df2=pd.DataFrame(dic1)

In [128]:
df2

x   y   z
0  10  30  50
1  20  40  60
2  30  50  70

# Kompleks DataFrame yapısı


In [7]:
np.random.seed(101) # bu kod seedi yani tohumu temsil ediyor. her seferinde tekrar rasgele değer üretmiyor.

df3=pd.DataFrame(np.random.randn(5,5),columns=" Val1 Val2 Val3 Val4 Val5".split(),index="a b c d e ".split() )
df3

Val1      Val2      Val3      Val4      Val5
a  2.706850  0.628133  0.907969  0.503826  0.651118
b -0.319318 -0.848077  0.605965 -2.018168  0.740122
c  0.528813 -0.589001  0.188695 -0.758872 -0.933237
d  0.955057  0.190794  1.978757  2.605967  0.683509
e  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [8]:
random_matrix = np.random.randn(5, 3)
print(random_matrix)

[[ 0.39052784  0.16690464  0.18450186]
 [ 0.80770591  0.07295968  0.63878701]
 [ 0.3296463  -0.49710402 -0.7540697 ]
 [-0.9434064   0.48475165 -0.11677332]
 [ 1.9017548   0.23812696  1.99665229]]


In [9]:
df3[["Val1","Val3"]]


Val1      Val3
a  2.706850  0.907969
b -0.319318  0.605965
c  0.528813  0.188695
d  0.955057  1.978757
e  0.302665 -1.706086

In [10]:
df3[["Val1","Val3"]]

Val1      Val3
a  2.706850  0.907969
b -0.319318  0.605965
c  0.528813  0.188695
d  0.955057  1.978757
e  0.302665 -1.706086

In [148]:
df3["a":"d"]

Val1      Val2      Val3      Val4      Val5
a  2.706850  0.628133  0.907969  0.503826  0.651118
b -0.319318 -0.848077  0.605965 -2.018168  0.740122
c  0.528813 -0.589001  0.188695 -0.758872 -0.933237
d  0.955057  0.190794  1.978757  2.605967  0.683509

In [155]:
df3[["Val2","Val4"]]

Val2      Val4
a  0.628133  0.503826
b -0.848077 -2.018168
c -0.589001 -0.758872
d  0.190794  2.605967
e  1.693723 -1.159119

In [11]:
array_1=np.random.randint(1,100,(5,5))
df4=pd.DataFrame(data=array_1,columns=" Val1 Val2 Val3 Val4 Val5".split(),index="a b c d e ".split() )
df4

Val1  Val2  Val3  Val4  Val5
a    55    87    10    46     3
b    19    59    93    12    11
c    95    36    29     4    84
d    85    48    15    70    61
e    70    52     7    89    72

In [12]:
# a dan d ye kadar olan sayıları karşımıza getirmiş oldu
df4.loc["a":"d"]

Val1  Val2  Val3  Val4  Val5
a    55    87    10    46     3
b    19    59    93    12    11
c    95    36    29     4    84
d    85    48    15    70    61

In [13]:
# index mantığı ile 
df4.iloc[0:4]

Val1  Val2  Val3  Val4  Val5
a    55    87    10    46     3
b    19    59    93    12    11
c    95    36    29     4    84
d    85    48    15    70    61

# loc iloc komutları

In [17]:
df4.iloc[:,[3]]

Val4
a    46
b    12
c     4
d    70
e    89

In [1]:
import pandas as pd
import numpy as np

In [31]:
df4.iloc[[2,4],[3]]

Val4
c     4
e    89

In [2]:
array_2=np.random.randint(10,300,(10,10))
np.random.seed(101)
df5=pd.DataFrame(data=array_2,index="Daniel Katie Selena Taylor Shelby Tom Joseph Gisselle Thomas Anastasia".split(),columns="1.Score 2.Score 3.Score 4.Score 5.Score 6.Score 7.Score 8.Score 9.Score 10.Score".split())
df5

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel         153      174       34       22      213      276      118   
Katie          215      163      193      198      154      239      115   
Selena         140      166      237       79      241      262      194   
Taylor         270      246      271      266      198       50      287   
Shelby          24      140      232       19       92      202      108   
Tom             32      122      182       59       60       63       53   
Joseph         114       45      206      283      247      132      171   
Gisselle        36       34       78      243       62       33      284   
Thomas          43      111      122      206      230       91      161   
Anastasia       46      172      233       98       34       83      281   

           8.Score  9.Score  10.Score  
Daniel         262      215       225  
Katie          220       91       165  
Selena          89      140       220  
Taylor         101      237       227  
Shelby         173       77       242  
Tom            126       25       120  
Joseph         297      131       199  
Gisselle       231      179        63  
Thomas          77      245       138  
Anastasia      260      283       198

In [4]:
df5.loc[["Daniel"]]


1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel      153      174       34       22      213      276      118   

        8.Score  9.Score  10.Score  
Daniel      262      215       225

In [5]:
df5.loc["Daniel":"Gisselle",["3.Score"]]

3.Score
Daniel         34
Katie         193
Selena        237
Taylor        271
Shelby        232
Tom           182
Joseph        206
Gisselle       78

In [56]:
df5.loc["Daniel":"Gisselle",["3.Score"]].iloc[1:3,]

3.Score
Katie        50
Selena      233

In [59]:
df5>200

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel       False    False    False    False    False    False    False   
Katie        False    False    False    False    False    False    False   
Selena       False    False     True    False    False     True     True   
Taylor        True    False    False     True    False    False    False   
Shelby        True    False    False     True     True    False    False   
Tom           True    False    False     True     True    False    False   
Joseph       False    False    False    False     True     True     True   
Gisselle      True    False     True    False     True     True    False   
Thomas       False    False    False     True     True    False     True   
Anastasia     True     True    False    False    False    False    False   

           8.Score  9.Score  10.Score  
Daniel        True     True      True  
Katie        False     True      True  
Selena       False    False     False  
Taylor       False     True      True  
Shelby       False     True      True  
Tom          False     True     False  
Joseph       False     True     False  
Gisselle     False    False      True  
Thomas        True    False     False  
Anastasia    False    False      True

In [61]:
df5[df5<50]

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel        21.0      NaN      NaN      NaN      NaN      NaN      NaN   
Katie          NaN     15.0      NaN      NaN      NaN      NaN      NaN   
Selena         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
Taylor         NaN     17.0      NaN      NaN      NaN     10.0      NaN   
Shelby         NaN      NaN      NaN      NaN      NaN     40.0     20.0   
Tom            NaN      NaN      NaN      NaN      NaN      NaN      NaN   
Joseph         NaN     38.0     13.0     24.0      NaN      NaN      NaN   
Gisselle       NaN      NaN      NaN      NaN      NaN      NaN      NaN   
Thomas         NaN     31.0     33.0      NaN      NaN      NaN      NaN   
Anastasia      NaN      NaN      NaN      NaN      NaN      NaN      NaN   

           8.Score  9.Score  10.Score  
Daniel         NaN      NaN       NaN  
Katie          NaN      NaN       NaN  
Selena         NaN      NaN       NaN  
Taylor         NaN      NaN       NaN  
Shelby         NaN      NaN       NaN  
Tom            NaN      NaN       NaN  
Joseph         NaN      NaN       NaN  
Gisselle       NaN      NaN       NaN  
Thomas         NaN     37.0      15.0  
Anastasia      NaN      NaN       NaN

In [6]:
df5[df5[["1.Score"]]>100]


1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel       153.0      NaN      NaN      NaN      NaN      NaN      NaN   
Katie        215.0      NaN      NaN      NaN      NaN      NaN      NaN   
Selena       140.0      NaN      NaN      NaN      NaN      NaN      NaN   
Taylor       270.0      NaN      NaN      NaN      NaN      NaN      NaN   
Shelby         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
Tom            NaN      NaN      NaN      NaN      NaN      NaN      NaN   
Joseph       114.0      NaN      NaN      NaN      NaN      NaN      NaN   
Gisselle       NaN      NaN      NaN      NaN      NaN      NaN      NaN   
Thomas         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
Anastasia      NaN      NaN      NaN      NaN      NaN      NaN      NaN   

           8.Score  9.Score  10.Score  
Daniel         NaN      NaN       NaN  
Katie          NaN      NaN       NaN  
Selena         NaN      NaN       NaN  
Taylor         NaN      NaN       NaN  
Shelby         NaN      NaN       NaN  
Tom            NaN      NaN       NaN  
Joseph         NaN      NaN       NaN  
Gisselle       NaN      NaN       NaN  
Thomas         NaN      NaN       NaN  
Anastasia      NaN      NaN       NaN

In [7]:
df5

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel         153      174       34       22      213      276      118   
Katie          215      163      193      198      154      239      115   
Selena         140      166      237       79      241      262      194   
Taylor         270      246      271      266      198       50      287   
Shelby          24      140      232       19       92      202      108   
Tom             32      122      182       59       60       63       53   
Joseph         114       45      206      283      247      132      171   
Gisselle        36       34       78      243       62       33      284   
Thomas          43      111      122      206      230       91      161   
Anastasia       46      172      233       98       34       83      281   

           8.Score  9.Score  10.Score  
Daniel         262      215       225  
Katie          220       91       165  
Selena          89      140       220  
Taylor         101      237       227  
Shelby         173       77       242  
Tom            126       25       120  
Joseph         297      131       199  
Gisselle       231      179        63  
Thomas          77      245       138  
Anastasia      260      283       198

In [8]:
df_copy=df5.copy()


In [9]:
df_copy

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel         153      174       34       22      213      276      118   
Katie          215      163      193      198      154      239      115   
Selena         140      166      237       79      241      262      194   
Taylor         270      246      271      266      198       50      287   
Shelby          24      140      232       19       92      202      108   
Tom             32      122      182       59       60       63       53   
Joseph         114       45      206      283      247      132      171   
Gisselle        36       34       78      243       62       33      284   
Thomas          43      111      122      206      230       91      161   
Anastasia       46      172      233       98       34       83      281   

           8.Score  9.Score  10.Score  
Daniel         262      215       225  
Katie          220       91       165  
Selena          89      140       220  
Taylor         101      237       227  
Shelby         173       77       242  
Tom            126       25       120  
Joseph         297      131       199  
Gisselle       231      179        63  
Thomas          77      245       138  
Anastasia      260      283       198

In [16]:
#sutun ekleme 
df_copy["Sum"] = df_copy.loc[:, "1.Score":"10.Score"].sum(axis=1)

In [17]:
df_copy

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel         153      174       34       22      213      276      118   
Katie          215      163      193      198      154      239      115   
Selena         140      166      237       79      241      262      194   
Taylor         270      246      271      266      198       50      287   
Shelby          24      140      232       19       92      202      108   
Tom             32      122      182       59       60       63       53   
Joseph         114       45      206      283      247      132      171   
Gisselle        36       34       78      243       62       33      284   
Thomas          43      111      122      206      230       91      161   
Anastasia       46      172      233       98       34       83      281   

           8.Score  9.Score  10.Score   Sum  
Daniel         262      215       225  1692  
Katie          220       91       165  1753  
Selena          89      140       220  1768  
Taylor         101      237       227  2153  
Shelby         173       77       242  1309  
Tom            126       25       120   842  
Joseph         297      131       199  1825  
Gisselle       231      179        63  1243  
Thomas          77      245       138  1424  
Anastasia      260      283       198  1688

In [21]:
df_copy["Mean"]=df_copy.iloc[:,0:10].mean(axis=1)

In [22]:
df_copy

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel         153      174       34       22      213      276      118   
Katie          215      163      193      198      154      239      115   
Selena         140      166      237       79      241      262      194   
Taylor         270      246      271      266      198       50      287   
Shelby          24      140      232       19       92      202      108   
Tom             32      122      182       59       60       63       53   
Joseph         114       45      206      283      247      132      171   
Gisselle        36       34       78      243       62       33      284   
Thomas          43      111      122      206      230       91      161   
Anastasia       46      172      233       98       34       83      281   

           8.Score  9.Score  10.Score   Sum   Mean  
Daniel         262      215       225  1692  169.2  
Katie          220       91       165  1753  175.3  
Selena          89      140       220  1768  176.8  
Taylor         101      237       227  2153  215.3  
Shelby         173       77       242  1309  130.9  
Tom            126       25       120   842   84.2  
Joseph         297      131       199  1825  182.5  
Gisselle       231      179        63  1243  124.3  
Thomas          77      245       138  1424  142.4  
Anastasia      260      283       198  1688  168.8

In [23]:
df_copy[10]=df_copy["Mean"]

In [27]:
df_copy["Std"]=df_copy.loc[:,"1.Score":"10.Score"].std(axis=1)

In [28]:
df_copy

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel         153      174       34       22      213      276      118   
Katie          215      163      193      198      154      239      115   
Selena         140      166      237       79      241      262      194   
Taylor         270      246      271      266      198       50      287   
Shelby          24      140      232       19       92      202      108   
Tom             32      122      182       59       60       63       53   
Joseph         114       45      206      283      247      132      171   
Gisselle        36       34       78      243       62       33      284   
Thomas          43      111      122      206      230       91      161   
Anastasia       46      172      233       98       34       83      281   

           8.Score  9.Score  10.Score   Sum   Mean     10        Std  
Daniel         262      215       225  1692  169.2  169.2  88.192718  
Katie          220       91       165  1753  175.3  175.3  47.039109  
Selena          89      140       220  1768  176.8  176.8  64.347667  
Taylor         101      237       227  2153  215.3  215.3  78.912117  
Shelby         173       77       242  1309  130.9  130.9  80.530808  
Tom            126       25       120   842   84.2   84.2  50.437640  
Joseph         297      131       199  1825  182.5  182.5  79.671897  
Gisselle       231      179        63  1243  124.3  124.3  98.905173  
Thomas          77      245       138  1424  142.4  142.4  67.340264  
Anastasia      260      283       198  1688  168.8  168.8  96.929298

In [30]:
df_copy["Std"]=df_copy.loc[:,"1.Score":"10.Score"].std(axis=1)

In [31]:
df_copy["Median"]=df_copy.loc[:,"1.Score":"10.Score"].median(axis=1)

In [32]:
df_copy["Var"]=df_copy.loc[:,"1.Score":"10.Score"].var(axis=1)

In [33]:
df_copy

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel         153      174       34       22      213      276      118   
Katie          215      163      193      198      154      239      115   
Selena         140      166      237       79      241      262      194   
Taylor         270      246      271      266      198       50      287   
Shelby          24      140      232       19       92      202      108   
Tom             32      122      182       59       60       63       53   
Joseph         114       45      206      283      247      132      171   
Gisselle        36       34       78      243       62       33      284   
Thomas          43      111      122      206      230       91      161   
Anastasia       46      172      233       98       34       83      281   

           8.Score  9.Score  10.Score   Sum   Mean     10        Std  Median  \
Daniel         262      215       225  1692  169.2  169.2  88.192718   193.5   
Katie          220       91       165  1753  175.3  175.3  47.039109   179.0   
Selena          89      140       220  1768  176.8  176.8  64.347667   180.0   
Taylor         101      237       227  2153  215.3  215.3  78.912117   241.5   
Shelby         173       77       242  1309  130.9  130.9  80.530808   124.0   
Tom            126       25       120   842   84.2   84.2  50.437640    61.5   
Joseph         297      131       199  1825  182.5  182.5  79.671897   185.0   
Gisselle       231      179        63  1243  124.3  124.3  98.905173    70.5   
Thomas          77      245       138  1424  142.4  142.4  67.340264   130.0   
Anastasia      260      283       198  1688  168.8  168.8  96.929298   185.0   

                   Var  
Daniel     7777.955556  
Katie      2212.677778  
Selena     4140.622222  
Taylor     6227.122222  
Shelby     6485.211111  
Tom        2543.955556  
Joseph     6347.611111  
Gisselle   9782.233333  
Thomas     4534.711111  
Anastasia  9395.288889

In [37]:
df_copy.drop([10],axis=1,inplace=True)

In [38]:
df_copy

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel         153      174       34       22      213      276      118   
Katie          215      163      193      198      154      239      115   
Selena         140      166      237       79      241      262      194   
Taylor         270      246      271      266      198       50      287   
Shelby          24      140      232       19       92      202      108   
Tom             32      122      182       59       60       63       53   
Joseph         114       45      206      283      247      132      171   
Gisselle        36       34       78      243       62       33      284   
Thomas          43      111      122      206      230       91      161   
Anastasia       46      172      233       98       34       83      281   

           8.Score  9.Score  10.Score   Sum   Mean        Std  Median  \
Daniel         262      215       225  1692  169.2  88.192718   193.5   
Katie          220       91       165  1753  175.3  47.039109   179.0   
Selena          89      140       220  1768  176.8  64.347667   180.0   
Taylor         101      237       227  2153  215.3  78.912117   241.5   
Shelby         173       77       242  1309  130.9  80.530808   124.0   
Tom            126       25       120   842   84.2  50.437640    61.5   
Joseph         297      131       199  1825  182.5  79.671897   185.0   
Gisselle       231      179        63  1243  124.3  98.905173    70.5   
Thomas          77      245       138  1424  142.4  67.340264   130.0   
Anastasia      260      283       198  1688  168.8  96.929298   185.0   

                   Var  
Daniel     7777.955556  
Katie      2212.677778  
Selena     4140.622222  
Taylor     6227.122222  
Shelby     6485.211111  
Tom        2543.955556  
Joseph     6347.611111  
Gisselle   9782.233333  
Thomas     4534.711111  
Anastasia  9395.288889

In [40]:
df_copy

1.Score  2.Score  3.Score  4.Score  5.Score  6.Score  7.Score  \
Daniel         153      174       34       22      213      276      118   
Katie          215      163      193      198      154      239      115   
Selena         140      166      237       79      241      262      194   
Taylor         270      246      271      266      198       50      287   
Shelby          24      140      232       19       92      202      108   
Tom             32      122      182       59       60       63       53   
Joseph         114       45      206      283      247      132      171   
Thomas          43      111      122      206      230       91      161   
Anastasia       46      172      233       98       34       83      281   

           8.Score  9.Score  10.Score   Sum   Mean        Std  Median  \
Daniel         262      215       225  1692  169.2  88.192718   193.5   
Katie          220       91       165  1753  175.3  47.039109   179.0   
Selena          89      140       220  1768  176.8  64.347667   180.0   
Taylor         101      237       227  2153  215.3  78.912117   241.5   
Shelby         173       77       242  1309  130.9  80.530808   124.0   
Tom            126       25       120   842   84.2  50.437640    61.5   
Joseph         297      131       199  1825  182.5  79.671897   185.0   
Thomas          77      245       138  1424  142.4  67.340264   130.0   
Anastasia      260      283       198  1688  168.8  96.929298   185.0   

                   Var  
Daniel     7777.955556  
Katie      2212.677778  
Selena     4140.622222  
Taylor     6227.122222  
Shelby     6485.211111  
Tom        2543.955556  
Joseph     6347.611111  
Thomas     4534.711111  
Anastasia  9395.288889

In [52]:
array100=np.random.randint(1,100,(6,5))
df6=pd.DataFrame(array100,columns="1.Note 2.Note 3.Note 4.Note 5.Note".split(),index="Selin Leyla Nazlı Hades Honos Aslı".split())

## Sütun ekleme silme komutları

In [53]:
df6

1.Note  2.Note  3.Note  4.Note  5.Note
Selin      48      15      70      61      70
Leyla      52       7      89      72      69
Nazlı      24      36      80      99      68
Hades      83      58      78      47       4
Honos      47      30      87      22      22
Aslı       82      24      95      72      21

In [54]:
df_copy1=df6.copy()

In [55]:
df_copy1["Mean"]=df_copy1.iloc[:,0:5].mean(axis=1)

In [56]:
df_copy1

1.Note  2.Note  3.Note  4.Note  5.Note  Mean
Selin      48      15      70      61      70  52.8
Leyla      52       7      89      72      69  57.8
Nazlı      24      36      80      99      68  61.4
Hades      83      58      78      47       4  54.0
Honos      47      30      87      22      22  41.6
Aslı       82      24      95      72      21  58.8

In [64]:
df_copy1.describe()

1.Note     2.Note     3.Note     4.Note     5.Note       Mean
count   6.000000   6.000000   6.000000   6.000000   6.000000   6.000000
mean   56.000000  28.333333  83.166667  62.166667  42.333333  54.400000
std    22.759613  17.851237   8.931219  26.056989  29.910979   7.021111
min    24.000000   7.000000  70.000000  22.000000   4.000000  41.600000
25%    47.250000  17.250000  78.500000  50.500000  21.250000  53.100000
50%    50.000000  27.000000  83.500000  66.500000  45.000000  55.900000
75%    74.500000  34.500000  88.500000  72.000000  68.750000  58.550000
max    83.000000  58.000000  95.000000  99.000000  70.000000  61.400000

In [106]:
import pandas as pd
import numpy as np

# Örnek veri çerçevesi oluşturma
df = pd.DataFrame(np.random.rand(30, 10), columns=[f"Column_{i+1}" for i in range(10)])

# Rastgele bazı hücreleri NaN (boş) yapma
for _ in range(15):  # Toplamda 15 hücreyi boş yapalım
    row_index = np.random.randint(0, 30)  # Satır indeksi seç
    col_index = np.random.randint(0, 10)  # Sütun indeksi seç
    df.iat[row_index, col_index] = np.nan  # Seçilen hücreyi NaN (boş) yap



In [85]:
df

Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0   0.048485  0.137869  0.186967  0.994318  0.520665  0.578790  0.734819   
1   0.402998  0.357224  0.952877  0.343632  0.865100  0.830278  0.538161   
2   0.701507  0.890480  0.159560  0.275573  0.672492  0.164303  0.701371   
3   0.043397  0.223937  0.575205  0.120434  0.500117  0.138010  0.052808   
4   0.949264  0.478167  0.461119  0.637289  0.324608  0.117578  0.051101   
5   0.651768  0.424569  0.656595  0.209161  0.659925  0.529623  0.748520   
6   0.695078  0.496867  0.975361  0.203528  0.299020  0.227656  0.048169   
7   0.630847  0.377942  0.013241  0.842219  0.384938  0.551666  0.710538   
8   0.412391  0.239791  0.968836  0.288557  0.147312  0.129340  0.944056   
9   0.700987  0.388531  0.942259  0.736491  0.238464  0.823774  0.760613   
10  0.845309  0.368647  0.436980  0.356598  0.239737  0.653378  0.390439   
11  0.195252       NaN  0.023305  0.548080  0.560908  0.074755  0.892271   
12  0.710853  0.881330  0.695290  0.266173  0.909964  0.579618  0.359687   
13  0.045510  0.885041  0.276421  0.580924  0.910662  0.992591  0.062224   
14  0.546931  0.264162  0.647213  0.462985  0.631007       NaN  0.222381   
15  0.302624  0.609272  0.085001  0.319178  0.815499  0.872406  0.890708   
16  0.162610  0.184091  0.223771  0.001189  0.226782  0.930979  0.738519   
17  0.313479  0.380982  0.642812       NaN  0.130528  0.730565  0.005438   
18  0.631129  0.017791  0.838551  0.525546  0.370938  0.425750  0.265095   
19  0.520926  0.462383  0.067457       NaN  0.719619  0.450736  0.684777   
20  0.862654  0.011621  0.799915  0.953490  0.105180  0.447649  0.437774   
21       NaN  0.592082  0.184795  0.967445  0.879504  0.119520  0.690088   
22  0.793152  0.177025  0.342030  0.255531  0.232678  0.761117  0.943450   
23  0.336773  0.504141  0.023746  0.311636  0.857556  0.405957  0.575889   
24  0.768023  0.286670  0.305824  0.825904  0.570742  0.248130  0.012546   
25  0.895562  0.755226  0.669032       NaN  0.062641  0.780621  0.067138   
26  0.547512  0.013428  0.071927  0.137375  0.341412  0.576656  0.207708   
27  0.759843  0.997649       NaN  0.361981  0.333948  0.743219  0.322229   
28  0.119351  0.571027  0.182720  0.468653  0.938128  0.443994  0.632374   
29  0.820479  0.312595  0.280868  0.297383  0.447656  0.589444  0.884912   

    Column_8  Column_9  Column_10  
0   0.541962  0.913154   0.807920  
1   0.922469  0.097146   0.102847  
2   0.487635  0.680678   0.521548  
3   0.178277  0.442368   0.877587  
4   0.637659       NaN   0.670260  
5   0.093757  0.784522   0.687242  
6        NaN  0.080104   0.607216  
7   0.675279  0.694565   0.342457  
8   0.351434  0.733568   0.913890  
9   0.394709  0.200188   0.712596  
10       NaN  0.362273   0.356502  
11  0.110623  0.625773   0.100850  
12  0.852634       NaN   0.780444  
13  0.928481       NaN   0.945382  
14  0.734495  0.799661   0.876622  
15  0.689910       NaN   0.407195  
16  0.917477  0.603498   0.454420  
17  0.650661  0.453049   0.200645  
18  0.446408  0.982653   0.752054  
19  0.732571  0.149805   0.608996  
20  0.620696  0.369172   0.395326  
21  0.904004  0.604129   0.491408  
22  0.477820  0.030844   0.592120  
23  0.691157  0.863851   0.833513  
24  0.332891  0.392887   0.801301  
25  0.132254  0.727103   0.251096  
26  0.923489  0.257744   0.694328  
27  0.379970  0.693347   0.396878  
28  0.285819  0.608647   0.685330  
29  0.998404  0.373907        NaN

In [80]:
condition=df.isnull().any(axis=1)

## isnull bos deger gorme

In [81]:
df[condition]

Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
4   0.949264  0.478167  0.461119  0.637289  0.324608  0.117578  0.051101   
6   0.695078  0.496867  0.975361  0.203528  0.299020  0.227656  0.048169   
10  0.845309  0.368647  0.436980  0.356598  0.239737  0.653378  0.390439   
11  0.195252       NaN  0.023305  0.548080  0.560908  0.074755  0.892271   
12  0.710853  0.881330  0.695290  0.266173  0.909964  0.579618  0.359687   
13  0.045510  0.885041  0.276421  0.580924  0.910662  0.992591  0.062224   
14  0.546931  0.264162  0.647213  0.462985  0.631007       NaN  0.222381   
15  0.302624  0.609272  0.085001  0.319178  0.815499  0.872406  0.890708   
17  0.313479  0.380982  0.642812       NaN  0.130528  0.730565  0.005438   
19  0.520926  0.462383  0.067457       NaN  0.719619  0.450736  0.684777   
21       NaN  0.592082  0.184795  0.967445  0.879504  0.119520  0.690088   
25  0.895562  0.755226  0.669032       NaN  0.062641  0.780621  0.067138   
27  0.759843  0.997649       NaN  0.361981  0.333948  0.743219  0.322229   
29  0.820479  0.312595  0.280868  0.297383  0.447656  0.589444  0.884912   

    Column_8  Column_9  Column_10  
4   0.637659       NaN   0.670260  
6        NaN  0.080104   0.607216  
10       NaN  0.362273   0.356502  
11  0.110623  0.625773   0.100850  
12  0.852634       NaN   0.780444  
13  0.928481       NaN   0.945382  
14  0.734495  0.799661   0.876622  
15  0.689910       NaN   0.407195  
17  0.650661  0.453049   0.200645  
19  0.732571  0.149805   0.608996  
21  0.904004  0.604129   0.491408  
25  0.132254  0.727103   0.251096  
27  0.379970  0.693347   0.396878  
29  0.998404  0.373907        NaN

In [83]:
# dolu verileri karşımıza getirdi
df[~condition]

Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0   0.048485  0.137869  0.186967  0.994318  0.520665  0.578790  0.734819   
1   0.402998  0.357224  0.952877  0.343632  0.865100  0.830278  0.538161   
2   0.701507  0.890480  0.159560  0.275573  0.672492  0.164303  0.701371   
3   0.043397  0.223937  0.575205  0.120434  0.500117  0.138010  0.052808   
5   0.651768  0.424569  0.656595  0.209161  0.659925  0.529623  0.748520   
7   0.630847  0.377942  0.013241  0.842219  0.384938  0.551666  0.710538   
8   0.412391  0.239791  0.968836  0.288557  0.147312  0.129340  0.944056   
9   0.700987  0.388531  0.942259  0.736491  0.238464  0.823774  0.760613   
16  0.162610  0.184091  0.223771  0.001189  0.226782  0.930979  0.738519   
18  0.631129  0.017791  0.838551  0.525546  0.370938  0.425750  0.265095   
20  0.862654  0.011621  0.799915  0.953490  0.105180  0.447649  0.437774   
22  0.793152  0.177025  0.342030  0.255531  0.232678  0.761117  0.943450   
23  0.336773  0.504141  0.023746  0.311636  0.857556  0.405957  0.575889   
24  0.768023  0.286670  0.305824  0.825904  0.570742  0.248130  0.012546   
26  0.547512  0.013428  0.071927  0.137375  0.341412  0.576656  0.207708   
28  0.119351  0.571027  0.182720  0.468653  0.938128  0.443994  0.632374   

    Column_8  Column_9  Column_10  
0   0.541962  0.913154   0.807920  
1   0.922469  0.097146   0.102847  
2   0.487635  0.680678   0.521548  
3   0.178277  0.442368   0.877587  
5   0.093757  0.784522   0.687242  
7   0.675279  0.694565   0.342457  
8   0.351434  0.733568   0.913890  
9   0.394709  0.200188   0.712596  
16  0.917477  0.603498   0.454420  
18  0.446408  0.982653   0.752054  
20  0.620696  0.369172   0.395326  
22  0.477820  0.030844   0.592120  
23  0.691157  0.863851   0.833513  
24  0.332891  0.392887   0.801301  
26  0.923489  0.257744   0.694328  
28  0.285819  0.608647   0.685330

# Dropna fonksiyonu and fillna
## boş değer bulunan sütunları düşürür


In [87]:
df_copy1

1.Note  2.Note  3.Note  4.Note  5.Note  Mean
Selin      48      15      70      61      70  52.8
Leyla      52       7      89      72      69  57.8
Nazlı      24      36      80      99      68  61.4
Hades      83      58      78      47       4  54.0
Honos      47      30      87      22      22  41.6
Aslı       82      24      95      72      21  58.8

In [92]:
df_copy1["Sashani"]=[np.nan,50,np.nan,np.nan,888,99]
df_copy1

1.Note  2.Note  3.Note  4.Note  5.Note  Mean  Sashani
Selin      48      15      70      61      70  52.8      NaN
Leyla      52       7      89      72      69  57.8     50.0
Nazlı      24      36      80      99      68  61.4      NaN
Hades      83      58      78      47       4  54.0      NaN
Honos      47      30      87      22      22  41.6    888.0
Aslı       82      24      95      72      21  58.8     99.0

In [96]:
df_copy1[df_copy1.isnull().any(axis=1)]

1.Note  2.Note  3.Note  4.Note  5.Note  Mean  Sashani
Selin      48      15      70      61      70  52.8      NaN
Nazlı      24      36      80      99      68  61.4      NaN
Hades      83      58      78      47       4  54.0      NaN

In [97]:
df_copy1.dropna()

1.Note  2.Note  3.Note  4.Note  5.Note  Mean  Sashani
Leyla      52       7      89      72      69  57.8     50.0
Honos      47      30      87      22      22  41.6    888.0
Aslı       82      24      95      72      21  58.8     99.0

In [98]:
df_copy1

1.Note  2.Note  3.Note  4.Note  5.Note  Mean  Sashani
Selin      48      15      70      61      70  52.8      NaN
Leyla      52       7      89      72      69  57.8     50.0
Nazlı      24      36      80      99      68  61.4      NaN
Hades      83      58      78      47       4  54.0      NaN
Honos      47      30      87      22      22  41.6    888.0
Aslı       82      24      95      72      21  58.8     99.0

In [107]:
df_copy1.fillna("[-----]")

1.Note  2.Note  3.Note  4.Note  5.Note  Mean  Sashani
Selin      48      15      70      61      70  52.8  [-----]
Leyla      52       7      89      72      69  57.8     50.0
Nazlı      24      36      80      99      68  61.4  [-----]
Hades      83      58      78      47       4  54.0  [-----]
Honos      47      30      87      22      22  41.6    888.0
Aslı       82      24      95      72      21  58.8     99.0

In [108]:
df_copy1.reset_index()

index  1.Note  2.Note  3.Note  4.Note  5.Note  Mean  Sashani
0  Selin      48      15      70      61      70  52.8      NaN
1  Leyla      52       7      89      72      69  57.8     50.0
2  Nazlı      24      36      80      99      68  61.4      NaN
3  Hades      83      58      78      47       4  54.0      NaN
4  Honos      47      30      87      22      22  41.6    888.0
5   Aslı      82      24      95      72      21  58.8     99.0

In [110]:
df_copy1["index"]="Name"

In [111]:
df_copy1

1.Note  2.Note  3.Note  4.Note  5.Note  Mean  Sashani index
Selin      48      15      70      61      70  52.8      NaN  Name
Leyla      52       7      89      72      69  57.8     50.0  Name
Nazlı      24      36      80      99      68  61.4      NaN  Name
Hades      83      58      78      47       4  54.0      NaN  Name
Honos      47      30      87      22      22  41.6    888.0  Name
Aslı       82      24      95      72      21  58.8     99.0  Name

In [115]:
df_copy1.drop(columns="index",inplace=True)

In [113]:
df_copy1.reset_index()

level_0  1.Note  2.Note  3.Note  4.Note  5.Note  Mean  Sashani index
0   Selin      48      15      70      61      70  52.8      NaN  Name
1   Leyla      52       7      89      72      69  57.8     50.0  Name
2   Nazlı      24      36      80      99      68  61.4      NaN  Name
3   Hades      83      58      78      47       4  54.0      NaN  Name
4   Honos      47      30      87      22      22  41.6    888.0  Name
5    Aslı      82      24      95      72      21  58.8     99.0  Name

In [114]:
df_copy1

1.Note  2.Note  3.Note  4.Note  5.Note  Mean  Sashani index
Selin      48      15      70      61      70  52.8      NaN  Name
Leyla      52       7      89      72      69  57.8     50.0  Name
Nazlı      24      36      80      99      68  61.4      NaN  Name
Hades      83      58      78      47       4  54.0      NaN  Name
Honos      47      30      87      22      22  41.6    888.0  Name
Aslı       82      24      95      72      21  58.8     99.0  Name

In [116]:
df_copy1

1.Note  2.Note  3.Note  4.Note  5.Note  Mean  Sashani
Selin      48      15      70      61      70  52.8      NaN
Leyla      52       7      89      72      69  57.8     50.0
Nazlı      24      36      80      99      68  61.4      NaN
Hades      83      58      78      47       4  54.0      NaN
Honos      47      30      87      22      22  41.6    888.0
Aslı       82      24      95      72      21  58.8     99.0